from stand_cooler_lib import SetStandDown, SetStandUp
from system_commands import PumpToFlowcell
from thermal_cycler_lib import SetThermalCyclerTemp
from thermal_cycler_lib import StopThermalCyclerControl
import time
from system_commands import AspirateFromBypass
from actuator_lib import TogglePos
print("Старт")
n = time.time()
SetStandDown()
time.sleep(7)
print("Установите на рабочее место штатив с реагентами и чип")
h = ''
while h != "work":
    h = input(">>")
    print(h)
SetStandUp()
time.sleep(7)
print("Начало отрабатывания алгоритма")

PumpToFlowcell(actPos=15, volume=743)
PumpToFlowcell(actPos=16, volume=743)
PumpToFlowcell(actPos=3, volume=1823)
for i in range(3):
    AspirateFromBypass(volume=623, aspirationRate=72, dispenseRate=2000)
PumpToFlowcell(actPos=8, aspirationRate=9, volume=623)
SetThermalCyclerTemp(temp=40)
time.sleep(30)
PumpToFlowcell(actPos=5, volume=743)
PumpToFlowcell(actPos=6, volume=743)
PumpToFlowcell(actPos=7, volume=743)
PumpToFlowcell(actPos=3, volume=743)
PumpToFlowcell(actPos=17, volume=743)
SetThermalCyclerTemp(temp=75)
time.sleep(30)
time.sleep(300)
SetThermalCyclerTemp(temp=40)
time.sleep(150)
for i in range(15):
    PumpToFlowcell(actPos=3, aspirationRate=9, volume=16)
    time.sleep(18)
for i in range(15):
    PumpToFlowcell(actPos=5, aspirationRate=9, volume=16)
    time.sleep(3)
time.sleep(90)
SetThermalCyclerTemp(temp=50)
for i in range(26):
    PumpToFlowcell(actPos=8, aspirationRate=9, volume=90)
    PumpToFlowcell(actPos=7, aspirationRate=9, volume=90)
    PumpToFlowcell(actPos=5, aspirationRate=9, volume=196)
    time.sleep(15)
PumpToFlowcell(actPos=3, volume=311)
SetThermalCyclerTemp(temp=20)
PumpToFlowcell(actPos=9, volume=743)
SetThermalCyclerTemp(temp=46)
time.sleep(300)
PumpToFlowcell(actPos=3, volume=311)
SetThermalCyclerTemp(temp=20)
PumpToFlowcell(actPos=1, volume=743)
PumpToFlowcell(actPos=2, volume=743)
PumpToFlowcell(actPos=4, volume=743)
PumpToFlowcell(actPos=3, volume=623)
PumpToFlowcell(actPos=8, aspirationRate=9, volume=203)
SetThermalCyclerTemp(temp=65)
time.sleep(60)
PumpToFlowcell(actPos=12, volume=743)
PumpToFlowcell(actPos=12, aspirationRate=9, volume=203)
SetThermalCyclerTemp(temp=40)
time.sleep(60)
PumpToFlowcell(actPos=3, volume=311)
SetThermalCyclerTemp(temp=60)
PumpToFlowcell(actPos=3, volume=311)
PumpToFlowcell(actPos=1, volume=131)
PumpToFlowcell(actPos=3, volume=65)
SetThermalCyclerTemp(temp=65)
time.sleep(20)
PumpToFlowcell(actPos=3, volume=16)
time.sleep(20)
SetThermalCyclerTemp(temp=22)
time.sleep(60)
PumpToFlowcell(actPos=3, volume=311)
PumpToFlowcell(actPos=2, volume=167)
PumpToFlowcell(actPos=3, volume=65)
time.sleep(15)
TogglePos(positionNumber=24)

# Imaging
print("Imaging")
h = ''
while h != "work":
    h = input(">>")
    print(h)

for i in range(250):
    print("Встраивание " + str(i + 2) + "-й буквы")
    a = time.time()
    SetThermalCyclerTemp(temp=60)
    PumpToFlowcell(actPos=3, volume=331)
    PumpToFlowcell(actPos=4, volume=167)
    PumpToFlowcell(actPos=3, volume=71)
    time.sleep(10)
    PumpToFlowcell(actPos=3, volume=623)
    PumpToFlowcell(actPos=1, volume=131)
    PumpToFlowcell(actPos=3, volume=64)
    SetThermalCyclerTemp(temp=65)
    time.sleep(20)
    PumpToFlowcell(actPos=3, volume=16)
    time.sleep(20)
    SetThermalCyclerTemp(temp=22)
    PumpToFlowcell(actPos=3, volume=311)
    PumpToFlowcell(actPos=2, volume=167)
    PumpToFlowcell(actPos=3, volume=64)
    time.sleep(15)
    print(a - time.time())
    # Imaging
    print("Imaging")
    h = ''
    while h != "work":
        h = input(">>")
        print(h)

# Начало второй части после просъёмки 251 буквы в одном направлении
# Объёмы указаны в микролитрах, переписать в шаги

PumpToFlowcell(actPos=3, volume=120)
SetThermalCyclerTemp(temp=60)
PumpToFlowcell(actPos=3, volume=120)
PumpToFlowcell(actPos=4, volume=60)
PumpToFlowcell(actPos=3, volume=20)
time.sleep(40)
PumpToFlowcell(actPos=3, volume=5)
time.sleep(35)
PumpToFlowcell(actPos=3, volume=250)
StopThermalCyclerControl()
PumpToFlowcell(actPos=3, volume=250)
SetThermalCyclerTemp(20)
time.sleep(120)
PumpToFlowcell(actPos=11, volume=300)
PumpToFlowcell(actPos=11, volume=75, aspirationRate=9)
SetThermalCyclerTemp(temp=38)
time.sleep(300)
PumpToFlowcell(actPos=3, volume=120)
SetThermalCyclerTemp(temp=50)
for i in range(8):
    PumpToFlowcell(actPos=8, volume=28, aspirationRate=9)
    PumpToFlowcell(actPos=7, volume=28, aspirationRate=9)
    PumpToFlowcell(actPos=6, volume=72, aspirationRate=9)
    time.sleep(15)
PumpToFlowcell(actPos=3, volume=120)
SetThermalCyclerTemp(20)
time.sleep(45)
PumpToFlowcell(actPos=10, volume=300)
PumpToFlowcell(actPos=10, volume=75, aspirationRate=9)
SetThermalCyclerTemp(38)
time.sleep(300)
PumpToFlowcell(actPos=3, volume=120)
PumpToFlowcell(actPos=8, volume=75, aspirationRate=9)
SetThermalCyclerTemp(temp=65)
time.sleep(60)
PumpToFlowcell(actPos=14, volume=300)
PumpToFlowcell(actPos=14, volume=75, aspirationRate=9)
SetThermalCyclerTemp(temp=40)
time.sleep(60)
PumpToFlowcell(actPos=3, volume=120)
# Second Base
SetThermalCyclerTemp(temp=60)
PumpToFlowcell(actPos=3, volume=120)
PumpToFlowcell(actPos=1, volume=45)
PumpToFlowcell(actPos=3, volume=20)
SetThermalCyclerTemp(temp=65)
time.sleep(20)
PumpToFlowcell(actPos=3, volume=5)
time.sleep(20)
SetThermalCyclerTemp(temp=22)
time.sleep(60)
PumpToFlowcell(actPos=3, volume=120)
PumpToFlowcell(actPos=2, volume=60)
PumpToFlowcell(actPos=3, volume=20)
time.sleep(15)
TogglePos(24)
# Imaging
print("Imaging")
h = ''
while h != "work":
    h = input(">>")
    print(h)

for i in range(250):
    SetThermalCyclerTemp(temp=60)
    PumpToFlowcell(actPos=3, volume=120)
    PumpToFlowcell(actPos=4, volume=60)
    PumpToFlowcell(actPos=3, volume=22)
    time.sleep(10)
    PumpToFlowcell(actPos=3, volume=250)
    PumpToFlowcell(actPos=1, volume=45)
    PumpToFlowcell(actPos=3, volume=20)
    SetThermalCyclerTemp(temp=65)
    time.sleep(20)
    PumpToFlowcell(actPos=3, volume=5)
    time.sleep(20)
    SetThermalCyclerTemp(temp=22)
    PumpToFlowcell(actPos=3, volume=120)
    PumpToFlowcell(actPos=2, volume=60)
    PumpToFlowcell(actPos=3, volume=20)
    time.sleep(15)
    TogglePos(24)
    # Imaging
    print("Imaging")
    h = ''
    while h != "work":
        h = input(">>")
        print(h)
